# Site settings
title: Trench-Ed
email: lbuckley@uw.edu
description: TrEnCh Education.
baseurl: "" # the subpath of your site, e.g. /blog
url: "trench-ed.github.io" # the base hostname & protocol for your site
author:
street_address: University of Washington
city: Seattle
state: WA
zip_code: 98109
country: United States of America
phone: (716) 555-5555

icon: fa-diamond # Font Awesome class for your site's icon

# Social settings
facebook_url:
github_url:
gitlab_url: https://github.com/trench-ed/
googleplus_url: ""
instagram_url:
linkedin_url: ""
pinterest_url:
slack_url:
twitter_url: ""

# Build settings
markdown: kramdown

sass:
style: compressed
