# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'About',               url: 'about'}
- {name: 'Climate Change',      url: 'climate'}
- {name: 'Physiology',          url: 'physiology'}
- {name: 'Gradients',           url: 'gradients'}
- {name: 'Historical Data',     url: 'history'}
- {name: 'Data Visualizations', url: 'RShiny'}
- {name: 'Resources',           url: 'resources'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'envelope', link:   'mailto:huckley@gmail.com'}

sharing_button_prompt: 'Feel free to share!'
